name: iconifyx_wordpress
description: >-
  WordPress Icons icons from Iconify, packaged for Flutter (271 icons, GPL license).
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  iconifyx_core:
    path: ../iconifyx_core

flutter:
  uses-material-design: false
  fonts:
    - family: Wordpress
      fonts:
        - asset: assets/fonts/Wordpress.ttf
    - family: WordpressSecondary
      fonts:
        - asset: assets/fonts/WordpressSecondary.ttf
