name: iconifyx_fxemoji
description: >-
  Firefox OS Emoji icons from Iconify, packaged for Flutter (117 icons, Apache 2.0 license).
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  iconifyx_core:
    path: ../iconifyx_core

flutter:
  uses-material-design: false
  fonts:
    - family: Fxemoji
      fonts:
        - asset: assets/fonts/Fxemoji.ttf
    - family: FxemojiSecondary
      fonts:
        - asset: assets/fonts/FxemojiSecondary.ttf
