name: iconifyx_ic
description: >-
  Google Material Icons icons from Iconify, packaged for Flutter (11914 icons, Apache 2.0 license).
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  iconifyx_core:
    path: ../iconifyx_core

flutter:
  uses-material-design: false
  fonts:
    - family: Ic
      fonts:
        - asset: assets/fonts/Ic.ttf
    - family: Ic_2
      fonts:
        - asset: assets/fonts/Ic_2.ttf
