name: iconifyx_streamline_freehand_color
description: >-
  Freehand color icons icons from Iconify, packaged for Flutter (307 icons, CC BY 4.0 license).
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  iconifyx_core:
    path: ../iconifyx_core

flutter:
  uses-material-design: false
  fonts:
    - family: StreamlineFreehandColor
      fonts:
        - asset: assets/fonts/StreamlineFreehandColor.ttf
