name: iconifyx_streamline_kameleon_color
description: >-
  Kameleon color icons icons from Iconify, packaged for Flutter (3 icons, CC BY 4.0 license).
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  iconifyx_core:
    path: ../iconifyx_core

flutter:
  uses-material-design: false
  fonts:
    - family: StreamlineKameleonColor
      fonts:
        - asset: assets/fonts/StreamlineKameleonColor.ttf
    - family: StreamlineKameleonColorSecondary
      fonts:
        - asset: assets/fonts/StreamlineKameleonColorSecondary.ttf
