name: iconifyx_tabler
description: >-
  Tabler Icons icons from Iconify, packaged for Flutter (25511 icons, MIT license).
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  iconifyx_core:
    path: ../iconifyx_core

flutter:
  uses-material-design: false
  fonts:
    - family: Tabler
      fonts:
        - asset: assets/fonts/Tabler.ttf
    - family: Tabler_2
      fonts:
        - asset: assets/fonts/Tabler_2.ttf
    - family: Tabler_3
      fonts:
        - asset: assets/fonts/Tabler_3.ttf
    - family: Tabler_4
      fonts:
        - asset: assets/fonts/Tabler_4.ttf
    - family: Tabler_5
      fonts:
        - asset: assets/fonts/Tabler_5.ttf
    - family: TablerSecondary
      fonts:
        - asset: assets/fonts/TablerSecondary.ttf
