name: iconifyx_fontelico
description: >-
  Fontelico icons from Iconify, packaged for Flutter (34 icons, CC BY SA license).
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  iconifyx_core:
    path: ../iconifyx_core

flutter:
  uses-material-design: false
  fonts:
    - family: Fontelico
      fonts:
        - asset: assets/fonts/Fontelico.ttf
