name: iconifyx_cryptocurrency
description: >-
  Cryptocurrency Icons icons from Iconify, packaged for Flutter (489 icons, CC0 1.0 license).
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  iconifyx_core:
    path: ../iconifyx_core

flutter:
  uses-material-design: false
  fonts:
    - family: Cryptocurrency
      fonts:
        - asset: assets/fonts/Cryptocurrency.ttf
    - family: CryptocurrencySecondary
      fonts:
        - asset: assets/fonts/CryptocurrencySecondary.ttf
