name: iconifyx_temaki
description: >-
  Temaki icons from Iconify, packaged for Flutter (555 icons, CC0 license).
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  iconifyx_core:
    path: ../iconifyx_core

flutter:
  uses-material-design: false
  fonts:
    - family: Temaki
      fonts:
        - asset: assets/fonts/Temaki.ttf
    - family: TemakiSecondary
      fonts:
        - asset: assets/fonts/TemakiSecondary.ttf
