name: iconifyx_token_branded
description: >-
  Web3 Icons Branded icons from Iconify, packaged for Flutter (660 icons, MIT license).
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  iconifyx_core:
    path: ../iconifyx_core

flutter:
  uses-material-design: false
  fonts:
    - family: TokenBranded
      fonts:
        - asset: assets/fonts/TokenBranded.ttf
    - family: TokenBrandedSecondary
      fonts:
        - asset: assets/fonts/TokenBrandedSecondary.ttf
